name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: npm install
        working-directory: functions/
        run: npm install --prefer-offline --no-audit
      - name: build
        working-directory: functions/
        run: npm run build
      - name: npm test
        working-directory: functions/
        run: npm test
