name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: browniebroke/read-nvmrc-action@v1 # Read node version from `.nvmrc` file
        id: nvmrc
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"
          cache: "npm"
          cache-dependency-path: functions/package-lock.json
      - name: npm install
        env:
          CI: true
        working-directory: functions/
        run: npm install --prefer-offline --no-audit
      - name: build
        working-directory: functions/
        run: npm run build
      - name: npm test
        working-directory: functions/
        run: npm test
